export const APPOINTMENT_STATUS_PENDING = 'PENDIENTE';
export const APPOINTMENT_STATUS_CONFIRMED = 'CONFIRMADA';

export const ACTIVE_APPOINTMENT_STATUSES = [APPOINTMENT_STATUS_PENDING, APPOINTMENT_STATUS_CONFIRMED];
