name: CI SONARQUBE

on:
  push:
    branches: [develop, main]
  pull_request:
    types: [opened, synchronize, reopened]

    paths:
      - "frontend/**"
      - "backend/**"
      - ".github/workflows/ci-sonarqube.yml"

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

          cache-dependency-path: |
            frontend/pnpm-lock.yaml
            backend/pnpm-lock.yaml

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Test Frontend (Coverage)
        working-directory: ./frontend
        run: pnpm test:coverage

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: pnpm install --frozen-lockfile

      - name: Test Backend (Coverage)
        working-directory: ./backend
        run: pnpm test:cov

      - name: SonarQube Scan Fullstack
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=umssy-is-organization
            -Dsonar.projectKey=UMSSY_umssy-app
            -Dsonar.sources=frontend/src,backend/src
            -Dsonar.tests=frontend/src,backend/src,backend/test
            -Dsonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,backend/src/**/*.spec.ts,backend/test/**/*.e2e-spec.ts
            -Dsonar.exclusions=frontend/src/app/layout.tsx,backend/src/main.ts,backend/src/**/*.module.ts,backend/src/**/*.interface.ts,backend/src/**/*.dto.ts,backend/src/**/*.entity.ts
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
